version: 1
formatters:
  detailed:
    format: '%(asctime)s %(name)-12s %(levelname)-8s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  simple:
    format: '%(levelname)-8s %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/matrix-server.log
    maxBytes: 104857600
    backupCount: 10
    encoding: utf8

loggers:
  matrix:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  matrix.network:
    level: INFO
    handlers: [console, file]
    propagate: no

  matrix.database:
    level: INFO
    handlers: [file]
    propagate: no

  matrix.crypto:
    level: INFO
    handlers: [file]
    propagate: no

root:
  level: INFO
  handlers: [console]